welcome:
    path: /
    controller: App\Controller\WelcomeController::index

login_personnel:
    path: /login_personnel
    controller: App\Controller\LoginController::login

login_patient:
    path: /login_patient
    controller: App\Controller\LoginPatientController::login

registerPatient:
    path: /registerPatient
    controller: App\Controller\RegistrationPatientController::index

app_logout:
    path: /logout
    methods: GET

userNotLogout:
    path: /userNotLogout
    controller: App\Controller\UserNotLogoutController::index

listePatients:
    path: /listePatients
    controller: App\Controller\ListePatientsController::index

modifierPatients:
    path: /modifierPatients/{id}
    controller: App\Controller\ModifierPatientsController::index

ajouterPatients:
    path: /ajouterPatients
    controller: App\Controller\AjouterPatientsController::index

listeSejourPatients:
    path: /listeSejourPatients/{id}
    controller: App\Controller\ListeSejourPatientsController::index

modifierSejour:
    path: /modifierSejour/{idsejour}/{id}
    controller: App\Controller\ModifierSejourController::index

ajouterSejours:
    path: /ajouterSejours/{id}
    controller: App\Controller\AjouterSejoursController::index

listeUtilisateurs:
    path: /listeUtilisateurs
    controller: App\Controller\ListeUtilisateursController::index

modifierUtilisateur:
    path: /modifierUtilisateur
    controller: App\Controller\ModifierUtilisateurController::index

ajouterUtilisateurs:
    path: /ajouterUtilisateurs
    controller: App\Controller\AjouterUtilisateursController::index

prendreRdv:
    path: /prendreRdv
    controller: App\Controller\PrendreRdvController::index

listeRdv:
    path: /listeRdv
    controller: App\Controller\ListeRdvController::index

Confirmation:
    path: /confirmation/{etatRdv}/{id}
    controller: App\Controller\ConfirmationController::index

reservationRdv:
    path: /reservationRdv/{id}
    controller: App\Controller\ReservationRdvController::index
